### ISSUE TITLE
Verbesserung (Feature):

### ISSUE THREAD

**Issue by mikiline** [Apollon77/ioBroker.alexa#1]
ist das möglich?

- Bluetooth connection zu gerät "verbinden" und "trennen"
- spiele Radiosender "XY"

**Comment by Apollon77** [comment]
Bitte wenns geht ein Issue pro Feature und das ins Subject ... besserer Überblick :-) Danke!

**Comment by Apollon77** [comment]
Ääähm ... 

Radio: alexa.0.echo-devices.Seriennummer.Commands.TuneIn !? Dort den Station-Namen (oder auch Station-ID? Kannst du maltesten?) rein. Der State kommt nur wenn das Gerät als Capability auch "TUNE_IN" hat.

Bluetooth Devices die verbunden sind werden unter alexa.0.echo-devices.Seriennummer.Bluetooth gelistet und haben dort ein "connected"-Flag und ein "unpaire" als Button zum disconnecten.

Dann bliebe nur "connect" übrig ?!

**Comment by mikiline** [comment]
Der State "Connected" sagt mir doch nur ob eine Bluetooth Verbindung besteht oder nicht.
Ein "Unpair" will ich ja nicht ausführen, da man ja sonst wieder ein Pairing durchführen muss.

Sind mal beide Geräte "gepaired", dann können sie connected oder eben unconnected werden (oder sehe ich das falsch?)

**Comment by mikiline** [comment]
connected = true oder false funktioniert :-)
Die Lösung mit dem TuneIn Radio Namen....damit kann ich auch leben.

Tip Top. Danke!

**Comment by Apollon77** [comment]
Morgen gibts update, da ist dann Playerinfo dabei und damit kannst Du hier auch die station-ids setzen ... dann mach ich hier zu :-)
