### ISSUE TITLE
Routinen

### ISSUE THREAD

**Issue by Apollon77** [Apollon77/ioBroker.alexa#4]
Listen und Triggern

**Comment by sigi2345** [comment]
Hallo,

ideal wäre noch eine so Art Playlist wo er alle Infos aufzeichnet. 
Ich weis das geht teilweise mit den History Adapter. Aber ich meine das man alles zusammenfassen kann.
Basic-Table?

Infos:
Abgespielte Titel
Interpreten
Sender
Befehle an Alexa

Sigi

**Comment by Apollon77** [comment]
Ääähm ... falsches issue? Routinen hat nix mit Musik zu tun. Bitte in eigenes issue packen

**Comment by Apollon77** [comment]
bzw an sich ist das ja noch ein anderes Thema ... es ist die Frage in wieweit ein Adapter Historien afzeichnen sollte.
Die Frage ist: Wozu? Und wer nutzt das? Aber auch das wäre ein eigenens Issue :-)

**Comment by Apollon77** [comment]
kommt in 0.2.0
